version: '3'       # 1
services:          # 2
  db:
    image: mysql:5.7    # 3
    platform: linux/x86_64
    environment:                  # 4
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: outon_db
      MYSQL_USER: outon_adm
      MYSQL_PASSWORD: outon
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
                                  # 5
  django:
    build: .       # 6
    volumes:                  # 8
      - .:/outon_main
    depends_on:               # 10
      - db
    ports:
      - "8080:8080"
    tty: true


  index:
    build: ./index_miyatter
    volumes:
      - ./index_miyatter:/index_miyatter_main/
    depends_on:
      - db
    ports:
      - "8090:8090"
    tty: true
