# Generated by Django 4.0 on 2022-05-11 05:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('post_content', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'session_post',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=20)),
                ('session_type', models.CharField(default='dynamic', max_length=20)),
                ('session_publication_range', models.CharField(default='all', max_length=20)),
                ('session_status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.baseuser')),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
