# Generated by Django 4.0 on 2022-05-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_sessioncomment_delete_sessionpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionComment',
        ),
    ]
