# Generated by Django 4.0 on 2022-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_sessioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_lecture',
            field=models.BooleanField(default=False),
        ),
    ]
