# Generated by Django 4.0 on 2022-05-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_session_is_lecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionComment',
        ),
    ]
