# Generated by Django 4.0 on 2022-05-18 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_nick_name_nickname'),
        ('session', '0010_delete_sessioncomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionComment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_nick_name', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.baseuser')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
            options={
                'db_table': 'session_comment',
            },
        ),
    ]
