# Generated by Django 4.0 on 2022-05-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_nick_name_nickname'),
        ('session', '0011_sessioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sessioncomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to='accounts.baseuser'),
        ),
    ]
