# Generated by Django 4.0 on 2022-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_session_session_time_session_session_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
